checks:
  php: true
  javascript: true
filter:
  excluded_paths:
    - test/*
    - node_modules/*
    - build/*
    - artifacts/*
    - deployment/vendor/*
    - deployment/build/*
    - deployment/public/production/*
    - deployment/public/components/*

build:
  cache:
    disabled: true

  environment:
    google_chrome:
      use_latest: true

    php:
      version: 7.2

  dependencies:
    before:
      - export LATEST=$(nvm ls-remote | tail -1)
      - nvm install $LATEST
#      - nvm use $LATEST

  tests:
    override:
      -
        command: ./deployment/vendor/bin/phpunit -c phpunit.xml
        coverage:
          file: build/coverage.xml
          format: php-clover
