sudo: required
dist: trusty
language: php
php:
# for now testing 7.2 php only
#  - '7.1'
  - '7.2'
# mpdf/mpdf is not working with nightly
#  - hhvm
#  - nightly
before_script:
  composer install

notifications:
  email:
    recipients:
      - alabard@gmail.com
    on_success: change # default: change
    on_failure: change # default: always
