name: php

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  coverage: xdebug

            - name: tests
              run: |
                composer install --no-progress
                XDEBUG_MODE=coverage ./deployment/vendor/bin/phpunit --coverage-text
                cd ./deployment/composer-custom/resume-php-common
                composer install --no-progress
                XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-text

        # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
        # Docs: https://getcomposer.org/doc/articles/scripts.md

        # - name: Run test suite
        #   run: composer run-script test
